/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rogerio.app;

import br.com.rogerio.bll.FactoryFormasPagto;
import br.com.rogerio.enumerations.EnumFormaDePagto;
import br.com.rogerio.interfaces.Factory_Interface;
import br.com.rogerio.model.Produtos;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class FactoryView_FormaDePagto extends javax.swing.JFrame {

    FactoryFormasPagto fabrica;
    Produtos produto;

    /**
     * Creates new form FactoryView_FormaDePagto
     */
    public FactoryView_FormaDePagto() {
        initComponents();
        jTextAreaSaida.setLineWrap(true);

        jComboBoxFormasDePagamento.removeAllItems();
        jComboBoxFormasDePagamento.addItem("< Selecione a forma de pagamento >");
        for (EnumFormaDePagto forma : EnumFormaDePagto.values()) {
            jComboBoxFormasDePagamento.addItem(forma.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFactoryPagtos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDescricaoDoProduto = new javax.swing.JTextField();
        jTextFieldQuantProdutos = new javax.swing.JTextField();
        jTextFieldValorUnitProd = new javax.swing.JTextField();
        jComboBoxFormasDePagamento = new javax.swing.JComboBox<>();
        jButtonExecularPagamento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Padrão de Projeto Factory - Formas de Pagamento");
        setResizable(false);

        jLabel1.setText("Descrição do produto:");

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Valor:");

        jComboBoxFormasDePagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonExecularPagamento.setText("Pagar");
        jButtonExecularPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecularPagamentoActionPerformed(evt);
            }
        });

        jTextAreaSaida.setColumns(20);
        jTextAreaSaida.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaida);

        javax.swing.GroupLayout jPanelFactoryPagtosLayout = new javax.swing.GroupLayout(jPanelFactoryPagtos);
        jPanelFactoryPagtos.setLayout(jPanelFactoryPagtosLayout);
        jPanelFactoryPagtosLayout.setHorizontalGroup(
            jPanelFactoryPagtosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFactoryPagtosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelFactoryPagtosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFactoryPagtosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelFactoryPagtosLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldDescricaoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelFactoryPagtosLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldQuantProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelFactoryPagtosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelFactoryPagtosLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldValorUnitProd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButtonExecularPagamento)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFactoryPagtosLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jComboBoxFormasDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(209, 209, 209))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelFactoryPagtosLayout.setVerticalGroup(
            jPanelFactoryPagtosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFactoryPagtosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelFactoryPagtosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDescricaoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFactoryPagtosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQuantProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorUnitProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelFactoryPagtosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFormasDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExecularPagamento))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFactoryPagtos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFactoryPagtos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExecularPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecularPagamentoActionPerformed
        // TODO add your handling code here:
        try {
            String descricao = jTextFieldDescricaoDoProduto.getText();
            int quantidade = Integer.parseInt(jTextFieldQuantProdutos.getText());
            double preco = Double.parseDouble(jTextFieldValorUnitProd.getText());
            produto = new Produtos(descricao, quantidade, preco);

            fabrica = FactoryFormasPagto.getInstance();
            Factory_Interface objeto = fabrica.getProdutoEformaDePagto(
                    EnumFormaDePagto.valueOf(jComboBoxFormasDePagamento.getSelectedItem().toString()));
            jTextAreaSaida.setText(objeto.pagamentoDaCompra(produto));

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção!!!\n" + erro.getMessage());
        }
        jComboBoxFormasDePagamento.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonExecularPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactoryView_FormaDePagto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactoryView_FormaDePagto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactoryView_FormaDePagto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactoryView_FormaDePagto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactoryView_FormaDePagto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExecularPagamento;
    private javax.swing.JComboBox<String> jComboBoxFormasDePagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelFactoryPagtos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaida;
    private javax.swing.JTextField jTextFieldDescricaoDoProduto;
    private javax.swing.JTextField jTextFieldQuantProdutos;
    private javax.swing.JTextField jTextFieldValorUnitProd;
    // End of variables declaration//GEN-END:variables
}
